"""
hardware/export_lut.py
======================

Exports the Mamdani FIS as a lookup table (LUT) for a microcontroller.

Running a full Mamdani inference (fuzzify, 9 rules, 2001-point centroid) every
minute is possible on an ESP32, but a pre-computed table is simpler, faster
and bit-for-bit predictable. The table samples the control surface every
0.5 °C and every 1 %RH (61 x 71 points), stores outputs in tenths of a
percent as int16, and the sketch interpolates bilinearly between grid points.

Usage (from the project folder):
    python hardware/export_lut.py
writes hardware/esp32_fuzzy_ac/fuzzy_lut.h and prints the interpolation error.

`lut_lookup()` below is a line-by-line Python copy of the C function in the
sketch; tests/test_hardware_lut.py uses it to check the table's accuracy.
"""

from __future__ import annotations

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))

import fuzzy_controller as fc  # noqa: E402

T_MIN, T_MAX, T_STEP = 10.0, 40.0, 0.5
H_MIN, H_MAX, H_STEP = 20.0, 90.0, 1.0
T_N = int(round((T_MAX - T_MIN) / T_STEP)) + 1     # 61
H_N = int(round((H_MAX - H_MIN) / H_STEP)) + 1     # 71
HEADER_PATH = os.path.join(HERE, "esp32_fuzzy_ac", "fuzzy_lut.h")


def build_tables(fis: fc.RoomFIS | None = None) -> tuple[np.ndarray, np.ndarray]:
    """int16 tables [H_N][T_N] holding ac_power and fan_speed in tenths of %."""
    fis = fis or fc.DEFAULT_FIS
    t = np.linspace(T_MIN, T_MAX, T_N)
    h = np.linspace(H_MIN, H_MAX, H_N)
    T, H = np.meshgrid(t, h)
    ac, fan = fis.compute_many(T, H)
    return np.round(ac * 10).astype(np.int16), np.round(fan * 10).astype(np.int16)


def lut_lookup(table: np.ndarray, temp: float, hum: float) -> float:
    """Bilinear interpolation, identical to lutLookup() in the sketch. Returns %."""
    temp = min(max(temp, T_MIN), T_MAX)
    hum = min(max(hum, H_MIN), H_MAX)
    ft = (temp - T_MIN) / T_STEP
    fh = (hum - H_MIN) / H_STEP
    i0 = min(int(ft), T_N - 2)
    j0 = min(int(fh), H_N - 2)
    dt = ft - i0
    dh = fh - j0
    v00 = table[j0][i0]
    v10 = table[j0][i0 + 1]
    v01 = table[j0 + 1][i0]
    v11 = table[j0 + 1][i0 + 1]
    v = (v00 * (1 - dt) * (1 - dh) + v10 * dt * (1 - dh)
         + v01 * (1 - dt) * dh + v11 * dt * dh)
    return v / 10.0


def lut_error(ac_tab: np.ndarray, fan_tab: np.ndarray, fis: fc.RoomFIS | None = None,
              t_step: float = 0.1, h_step: float = 0.5) -> dict:
    """Max and mean absolute error of the LUT against the exact FIS on a finer grid."""
    fis = fis or fc.DEFAULT_FIS
    t = np.arange(T_MIN, T_MAX + 1e-9, t_step)
    h = np.arange(H_MIN, H_MAX + 1e-9, h_step)
    T, H = np.meshgrid(t, h)
    ac_ref, fan_ref = fis.compute_many(T, H)
    ac_lut = np.vectorize(lambda a, b: lut_lookup(ac_tab, a, b))(T, H)
    fan_lut = np.vectorize(lambda a, b: lut_lookup(fan_tab, a, b))(T, H)
    return {
        "ac_max": float(np.abs(ac_lut - ac_ref).max()),
        "ac_mean": float(np.abs(ac_lut - ac_ref).mean()),
        "fan_max": float(np.abs(fan_lut - fan_ref).max()),
        "fan_mean": float(np.abs(fan_lut - fan_ref).mean()),
        "points": int(T.size),
    }


def _c_array(name: str, table: np.ndarray) -> str:
    lines = [f"static const int16_t {name}[LUT_H_N][LUT_T_N] = {{"]
    for row in table:
        lines.append("  {" + ", ".join(str(int(v)) for v in row) + "},")
    lines.append("};")
    return "\n".join(lines)


def write_header(ac_tab: np.ndarray, fan_tab: np.ndarray, path: str = HEADER_PATH) -> str:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    text = f"""// fuzzy_lut.h  --  GENERATED by hardware/export_lut.py, do not edit by hand.
//
// Mamdani FIS (temperature, humidity) -> (ac_power, fan_speed) sampled on a grid.
// Values are tenths of a percent: ac_power -1000..1000 (negative = heating),
// fan_speed 0..1000. Row index = humidity, column index = temperature.
#pragma once
#include <stdint.h>

#define LUT_T_MIN  {T_MIN}f
#define LUT_T_MAX  {T_MAX}f
#define LUT_T_STEP {T_STEP}f
#define LUT_T_N    {T_N}
#define LUT_H_MIN  {H_MIN}f
#define LUT_H_MAX  {H_MAX}f
#define LUT_H_STEP {H_STEP}f
#define LUT_H_N    {H_N}

{_c_array("AC_LUT", ac_tab)}

{_c_array("FAN_LUT", fan_tab)}
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return path


def main() -> dict:
    ac_tab, fan_tab = build_tables()
    path = write_header(ac_tab, fan_tab)
    err = lut_error(ac_tab, fan_tab)
    size_kb = 2 * ac_tab.size * 2 / 1024
    print(f"Wrote {os.path.relpath(path, os.path.dirname(HERE))}  "
          f"({T_N} x {H_N} grid, 2 tables, {size_kb:.1f} KB of flash)")
    print(f"LUT accuracy over {err['points']} test points: "
          f"ac_power max |error| = {err['ac_max']:.2f} % (mean {err['ac_mean']:.3f} %), "
          f"fan_speed max |error| = {err['fan_max']:.2f} % (mean {err['fan_mean']:.3f} %)")
    return err


if __name__ == "__main__":
    main()
